### ISSUE TITLE
Example of parsing openRTB requests with the new API

### ISSUE THREAD

**Issue by astrekalova** [bsm/openrtb#10]
Hello,
I updated the dependency for this library today and noticed that parsing the openRTB requests has changed. What is the new equivalent to this command: 
req, err := openrtb.ParseRequest(r.Body)

Could you provide an example or point to documentation?

**Comment by nikolai-b** [comment]
From https://github.com/bsm/openrtb/blob/ff28769125b9f0079081544d5b529b98875b06e9/request.go#L34 you can just implement it yourself:
```
var req openrtb.BidRequest
var err error
err = json.NewDecoder(r.Body).Decode(&req)
```

**Comment by dim** [comment]
It's also documented in the README, please see https://github.com/bsm/openrtb#usage
