### ISSUE TITLE
Guidance Adding Native Ad Request and Native Ad Response

### ISSUE THREAD

**Issue by nightlyone** [bsm/openrtb#12]
What is your intention regarding http://www.iab.net/media/file/OpenRTB-Native-Ads-Specification-1_0-Final.pdf ?

Would an implementation be in scope of this package or should it be layered on top of it?

While taking a stab at providing the right structures for marshalling, I could only see re-use of the Video type, but MinDuration and MaxDuration are required instead of recommended in the OpenRTB Native Ads Specification.

At the moment I am leaning towards a subpackage "nativeads" importing "openrtb" and parsing the string in Native.Request there. That would allow matching Native.Ver with the ver field encoded the the structure in the request.

Another idea would be to provide a completely independent package and let the user of both packages do that.

Any recommendations?

**Comment by dim** [comment]
I would prefer to keep it all together but you could submit a PR with a sub-package. How about `github.com/bsm/openrtb/native`?

**Comment by dolzenko** [comment]
@nightlyone native support added in https://github.com/bsm/openrtb/commit/f0bcd59f9489259cc390b2540fb84d3f63f64685 and subsequent commits.
