### ISSUE TITLE
Reading native request

### ISSUE THREAD

**Issue by dougbarrett** [bsm/openrtb#28]
What is the best way going about reading a native request? I was intending on Native being a string object, but it looks like it's set as an Extension and I see there are json marshal and unmarshal functions associated to it. I have this, but haven't yet tested it:

    var native request.Request
    nativeBytes, err := json.Marshal(imp.Native.Request)
    if err != nil {
        return
    }
    
    err = json.Unmarshal(nativeBytes, &native)
    if err != nil {
        return
    }

**Comment by dolzenko** [comment]
@dougbarrett Extension is `[]byte` alias [0] so the code you provided should work. Let me know if you have any other questions.

[0] https://github.com/bsm/openrtb/blob/master/extension.go#L9

**Comment by dim** [comment]
Closing
