### ISSUE TITLE
imp.Secure and Misbehaving SSPs

### ISSUE THREAD

**Issue by marklr** [bsm/openrtb#33]
Hi,

I'm using the code in production and after seeing error rates go up post-integration with an SSP, I realized that they're sending auctions that specify the _secure_ tag as a string rather than an int.

I've resorted to forking to repo and specifying it as a json.Number - is maintaining a local fork my only solution or perhaps I could submit a PR?

Thanks,

**Comment by dim** [comment]
Hey, I know all too well who you are talking about. I thought they have
fixed the issue in their latest API version? I don't mind switching to
json.Number, as long as you add a little comment why this is required and
maybe a little test.

Thanks
