### ISSUE TITLE
Video sequence property

### ISSUE THREAD

**Issue by kozer** [bsm/openrtb#52]
When you set video sequence to 0, it automatically sets it's value to 1 when is marshalled.

**Comment by dim** [comment]
According to section 6.3.4 of the OpenRTB v2.5 spec:

> sequence: It is not explicitly included so the default of “1” should be assumed.

**Comment by kozer** [comment]
I set it explicitly to zero and keeps make it 1

**Comment by dim** [comment]
Well, for once `0` is the null-value for ints in Go. Additionally, Audio and Video sequences are `1` indexed in OpenRTB
