### ISSUE TITLE
Banner struck is improperly using the omitempty tag for the Pos field

### ISSUE THREAD

**Issue by rberner** [bsm/openrtb#55]
https://github.com/bsm/openrtb/blob/8d411108e2ccceff4fe33ddf98c33caa68c26760/banner.go#L20

At line 20 in banner.go:

``Pos  int  `json:"pos,omitempty"` ``

The omitempty tag is causing the field to be omitted when the value is 0. However, according to the OpenRTB spec, a value of 0 is valid for the pos field:
https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf

A potential fix would be to use an int pointer, which would change the value required to omit the field from 0 to nil.

``Pos  *int  `json:"pos,omitempty"` ``

**Comment by dim** [comment]
According to the spec, the value `0` means unknown, which is the default and the the same as omitting the attribute completely. I don't quite understand why you would need to set it to 0 explicitly?

**Comment by rberner** [comment]
Yeah, I agree. Was thinking about it incorrectly. Closing now.
