### ISSUE TITLE
Content Category typo

### ISSUE THREAD

**Issue by ollevche** [bsm/openrtb#73]
Hi! Seems like there's a typo in Content Category. [OpenRTB 2.5 listing](https://www.iab.com/wp-content/uploads/2016/03/OpenRTB-API-Specification-Version-2-5-FINAL.pdf#page=39) has **3-D Graphics** equal to **IAB19-1**, but in [openrtb.go](https://github.com/bsm/openrtb/blob/master/openrtb.go#L322) **ContentCategoryDGraphics** is set to **IAB19-13**.

**Comment by dim** [comment]
@ollevche thanks for pointing this out, good catch. Would you mind submitting a pull request for the change?

**Comment by ollevche** [comment]
Hi, there's another one in **7-12 Education**. The code must be **IAB5-1** instead of **IAB5-17**
