### ISSUE TITLE
Native request on different json node. 

### ISSUE THREAD

**Issue by shivakumarss** [bsm/openrtb#79]
Hi,

I have cloned bsm/openrtb to suit my requirement mentioned here in this ticket https://github.com/bsm/openrtb/issues/62 

- Now I am upgrading the bsm/openrtb version. to 3.x 
- Now since i am upgrading to bsm/openrtb 3.x i am thinking it there any way i can achieve this without cloning / modifying the source code  ?

Thanks a lot.

**Comment by mxmCherry** [comment]
> Now since i am upgrading to bsm/openrtb 3.x i am thinking it there any way i can achieve this without cloning / modifying the source code ?

No, openrtb/v3 did not add anything to allow this. You still need to adapt the code.

**Comment by mxmCherry** [comment]
@dim close? Not much can be done for non-std tags/keys.
