### ISSUE TITLE
SUA Browsers type is invalid

### ISSUE THREAD

**Issue by Katsukiniwa** [bsm/openrtb#95]
I found minor bug on sua.

According to IAB reference, Browsers fileld of sua type is `Array of BrandVersion`, but current it is `BrandVersion` .

<img width="685" alt="010" src="https://user-images.githubusercontent.com/35918681/212821967-1be2b994-04b3-4da3-9291-9613ec368d45.png">

https://iabtechlab.com/wp-content/uploads/2022/04/OpenRTB-2-6_FINAL.pdf

https://github.com/bsm/openrtb/blob/b106b7e1c3d86ac819f2327c89031e68f8f35961/sua.go#L6

I want to fix this bug, but I don't have authorization to this repository, so please fix someone else.

If I'm wrong in pointing this out, please ignore this issue and close.

**Comment by dim** [comment]
@Katsukiniwa could you please fork and [submit a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)?

**Comment by Katsukiniwa** [comment]
@dim 
https://github.com/bsm/openrtb/pull/96

Thanks, I opened pull request!
