### ISSUE TITLE
SUA source type is invalid 

### ISSUE THREAD

**Issue by MasatoraAtarashi** [bsm/openrtb#97]
According to IAB reference, Source fileld of sua type is integer, but current it is string.

<img width="911" alt="スクリーンショット 2023-02-09 19 41 48" src="https://user-images.githubusercontent.com/17522824/217790133-d1f09d07-af6c-4335-9769-db6c294476f7.png">

https://github.com/InteractiveAdvertisingBureau/AdCOM/blob/master/AdCOM%20v1.0%20FINAL.md#object--useragent-

https://github.com/bsm/openrtb/blob/56ba587d9d6af6042eafd147add6f058f2e562ab/sua.go#L12

This causes the following error when decoding json
```go
Unmarshal type error: expected=string, got=number, field=device.sua.source, offset=1282
```

**Comment by dim** [comment]
Hi, thnaks
